### ISSUE TITLE
Problem with saving and reading certain SFF files

### ISSUE THREAD

**Issue by KJ-Waller** [swharden/Spectrogram#20]
Hi Scott,

I'm experiencing some issues with saving SFF files, as some of the SFF files seem to be empty when I read them in Python. There are two ways I have found I can recreate the issue.

First of all, when using SaveData on a spectrogram which does not have a maxFreq value, I get empty spectrograms when reading the SFF file in Python. 

**C#**
```cs
(int sampleRate, double[] audio) = WavFile.ReadMono(filename);
spec = Spectrogram.Spectrogram(sampleRate, fttSize: 512, sstepSize: 200);
spec.Add(audio);

spec.SaveData("spectrogram.sff");
```

**Python**
```python
sff_spec = sffLib.SpectrogramFile('spectrogram.sff').values
```
At which point sff_spec is None.

Secondly, I also get the same problem when providing a maxFreq > 7999 in C# when instantiating the spectrogram. Even with setting the maxFreq = 7999, I get some SFF files that still contain no spectrogram data. One such example is [this file from the TESS dataset](https://dataverse.scholarsportal.info/file.xhtml?fileId=95662&version=1.0).

Is this a problem with the C# SaveData function or am I doing something wrong saving the SFF files?

Regards,
Kevin

**Comment by swharden** [comment]
I created some code based on your description:

```cs
(int sampleRate, double[] audio) = WavFile.ReadMono("../../../../../data/03-02-03-01-02-01-19.wav");
int fftSize = 1 << 12;
var spec = new Spectrogram(sampleRate, fftSize, stepSize: 300, maxFreq: 7999);
spec.Add(audio);
spec.SaveData("testDoor.sff");
```

This code run on the file you gave (renamed), this C# produces a SFF file that is viewable with the "SFF viewer" program in the dev folder. This means everything on the C#/SFF writing side is working well. I'll take a closer look at the Python side to see if there's an error reading this file...

![image](https://user-images.githubusercontent.com/4165489/88751947-bf7faf00-d126-11ea-91b7-0fd9bc011e96.png)

**Comment by swharden** [comment]
Indeed! Something is wrong with the python reading side...

Python's output indicates
```
Spectrogram from file: testDoorBig.sff
SFF version: 1.1      

Sample rate: 48000 Hz 
Step size: 300 samples
Step count: 701 steps 

FFT size: 4096        
FFT first index: 0    
FFT height: 682 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
FFT offset: 0 Hz      

Values per point: 1
Complex values: False
Bytes per point: 8
Decibels: False

Mel bin count: 0
image width: 189
image height: 170 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Time Resolution: 0.00625 sec/px
Frequency Resolution: 11.71875 Hz/px

First data byte: 256

Loaded testDoorBig.sff (32,130 values) in 22.28 ms

[[0.001 0.002 0.001 ... 0.    0.    0.   ]
 [0.    0.001 0.001 ... 0.    0.001 0.   ]
 [0.001 0.001 0.001 ... 0.001 0.    0.   ]
 ...
 [0.001 0.001 0.003 ... 0.002 0.005 0.003]
 [0.003 0.002 0.002 ... 0.001 0.    0.002]
 [0.003 0.002 0.001 ... 0.002 0.002 0.001]]
```

but these two numbers don't agree with each other. I'll keep working to figure out why

![image](https://user-images.githubusercontent.com/4165489/88752185-492f7c80-d127-11ea-803c-617c3ed5e8fb.png)

**Comment by swharden** [comment]
Yeah, setting `maxFreq: 3000` produces this. There is definitely something wrong **on the python side**.

![image](https://user-images.githubusercontent.com/4165489/88752782-c0b1db80-d128-11ea-9362-2b23d07fdbb1.png)

It's too late for me to get this working tonight, but I'll revisit this before long! Sorry for the inconvenience. If it's an option, saving the spectrogram as a PNG from C# may get you off the ground in a pinch

**Comment by swharden** [comment]
got it! Python was reading the image width from the SFF file expecting an `Int8` but it's really an `Int32` 🙈 Use the latest sffLib.py in this repo and let me know if it does the trick!
