### ISSUE TITLE
create filter module

### ISSUE THREAD

**Issue by swharden** [swharden/Spectrogram#26]
If you start with a signal, take the FFT, edit the complex numbers, then take the iFFT, you result with a signal whose spectral components can be filtered. Create a module to make filtering easy. Something like:
```cs
double[] audio = ReadWav("test.wav");
double[] filtered1 = FftSharp.Filter.LowPass(audio, frequency: 500);
double[] filtered2 = FftSharp.Filter.HighPass(audio, frequency: 500);
double[] filtered3 = FftSharp.Filter.BandPass(audio, frequency1: 300, frequency2: 500);
double[] filtered4 = FftSharp.Filter.BandStop(audio, frequency1: 300, frequency2: 500);
```

**Comment by swharden** [comment]
oops, this issue belongs in the FftSharp project:
https://github.com/swharden/FftSharp/issues/23

**Comment by vadd98** [comment]
Hi, sorry to open an old issue. 
I'd like to know if there is a way to apply FftSharp's filters while generating a spectrogram image using this library. I don't see any exposed filter method from SpectrogramGenerator
