### ISSUE TITLE
Spectrogram renders as solid color.

### ISSUE THREAD

**Issue by TheDJPHD** [swharden/Spectrogram#28]
Hello,
I am learning about Spectrograms and I would like to use this library to view spectrograms for the GTZAN music data set, which is a bunch of 30-second wav files at 22050hz. 

Whenever I Add() the song, which I read in using Spectrogram.WavFile.ReadMono(), and then produce the image, it is always comes out as a straight blue/purple image, depending on the ColorMap. 

I must be creating my spectrogram incorrectly, or something is wrong with my audio, though, I am confident my audio arrays are full of data. I even save them back to wav files and play them from my program. 

I guess a solid color bitmap would mean that every frequency is the same for the whole song. 

I am attaching one audio file here:
[SongSample.zip](https://github.com/swharden/Spectrogram/files/5192474/SongSample.zip)

Please let me know if you can help. 
Thank you,
James

**Comment by swharden** [comment]
Hi @TheDJPHD, I am very sorry it took this long to get back to you! This issue slipped off my radar and I just noticed it again this morning. I'm guessing you figured this out or moved on, but just in case someone ends up here after Googling I thought I'd share the answer:

```cs
(int sampleRate, double[] audio) = Spectrogram.WavFile.ReadMono("blues.00001.wav");
var spec = new Spectrogram.Spectrogram(sampleRate, fftSize: 1024, stepSize: 800);
spec.Add(audio);
spec.SaveImage("test.png", intensity: 2);
```

![image](https://user-images.githubusercontent.com/4165489/97812845-52624500-1c52-11eb-9cbb-bcf0c91e641f.png)
