### ISSUE TITLE
how to create best quality image with mel for low freq short (150 ms) sound?

### ISSUE THREAD

**Issue by AlexandrSpirin** [swharden/Spectrogram#38]
![Linear](https://user-images.githubusercontent.com/42524956/138005782-cb79aa0f-3be7-45a1-968b-909bd6d3e8f9.png)
![Mel](https://user-images.githubusercontent.com/42524956/138005788-e0a28842-01a1-4562-8438-f064774135bb.png)
![Need](https://user-images.githubusercontent.com/42524956/138005789-59f7ad08-64e8-467d-b0b4-960fecb795d0.png)

(the problem can be understood from the attached pictures: 1 - my linear, 2 - my mel, 3 - need)
i use 
fftSize = 1024
stepSize = 1
sampleRate = 44100

**Comment by swharden** [comment]
Hi @AlexandrSpirin, can you provide additional information about how you generated the last image? Is the whole image only 150 ms wide?

**Comment by AlexandrSpirin** [comment]
> Привет, @AlexandrSpirin , не могли бы вы предоставить дополнительную информацию о том, как вы сгенерировали последнее изображение? Ширина всего изображения составляет всего 150 мс?

Yes, last image for same sound (150 ms), i use EDM kick for example in WAV. This image can be obtained with "Edison" by Image Line

**Comment by AlexandrSpirin** [comment]
https://drive.google.com/file/d/14mqbJtz4HRRm-DuACueFrf28fGufKmfl/view?usp=sharing

Github does not allow attaching audio format files, file by link.

The picture shows a spectral pattern with a linear representation for the same sound. The picture is similar to what your library gives in linear mode
Perhaps this is not a spectrogram heatmap, but something else. It is important for me to get the correct display of low frequencies in mel mode.
It looks like your picture uses a voice that doesn't have enough low frequencies. But it also shows that not just pixels are used in displaying sound, but really a set of lines. It would be very cool if your library was capable of this.

![EdisonKickLinear](https://user-images.githubusercontent.com/42524956/138171302-9685cb82-83a5-4e39-a8d9-1a1d1a68754e.png)




> Привет @AlexandrSpirin ,
> 
> Я изо всех сил пытаюсь понять, что это за изображение на самом деле ... Это не похоже на тепловую карту спектрограммы
> 
> Я использую термин «тепловая карта спектрограммы» для определения прямоугольного изображения, где каждый квадратный цвет пикселя представляет мощность частоты в определенное время. Изображение, которое вы пытаетесь создать, не похоже на тепловую карту спектрограммы.
> 
> Скриншот Эдисона на https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins/Edison.htm показывает тепловую карту спектрограммы ... но это не выглядит нравится, какой у вас имидж. ![изображение](https://user-images.githubusercontent.com/4165489/138101710-b0095668-f1a4-4dce-b7bc-ef40536d4d91.png)
> 
> Конечно, цвета такие же, но изображение, которое вы пытаетесь создать, выглядит как серия линий, а не тепловая карта. Я не могу найти никаких примеров на странице Эдисона.
> 
> Как вы создали это изображение и возможно ли, что это не тепловая карта спектрограммы?
> 
> Также может быть полезно, если вы перетащите этот файл WAV в свой комментарий, чтобы мы оба могли быть уверены, что обсуждаем один и тот же сигнал.

**Comment by swharden** [comment]
For future reference [TempKick.zip](https://github.com/swharden/Spectrogram/files/7384828/TempKick.zip) 😉

**Comment by swharden** [comment]
> not just pixels are used in displaying sound, but really a set of lines. It would be very cool if your library was capable of this.

I think this is what may be making the discussion complicated. At this time I think it's best to keep this library focused on making spectrograms (the rectangular/pixel kind, and what [Wikipedia shows](https://en.wikipedia.org/wiki/Spectrogram) when you look-up the word).

I recognize there may be other ways to display spectral data, such as line plots, but that's probably outside the scope of this library. There are lots of great libraries to make line plots including https://scottplot.net 

All that said, I'll take a closer look at the WAV file you sent to see if I can make it look better than what you originally posted 👍

**Comment by swharden** [comment]
Hi @AlexandrSpirin, I'm sorry it took me so long to get to this! The latest [ScottPlot release](https://scottplot.net/changelog) took a lot more time than expected, then I got sucked into refactoring [FftSharp's windowing system](https://github.com/swharden/FftSharp)

Regarding this topic, I learned a lot more about the situation and will share what I found. First, here's some sample code which generates the following image:

```cs
static class Program
{
    static void Main()
    {
        // load data from the audio file
        (double[] values, int sampleRate) = ReadWavMono("data/kick.wav");

        // instantiate a spectrogram generator
        var sg = new Spectrogram.SpectrogramGenerator(sampleRate, fftSize: 4096, stepSize: 15, maxFreq: 5_000);

        // use a custom window to refine time and frequency resolution
        var window = new FftSharp.Windows.Hanning();
        double[] windowValues = window.Create(size: 1000);
        sg.SetWindow(windowValues);

        // use a custom colormap
        sg.Colormap = Spectrogram.Colormap.Magma;

        // pass audio data in for processing then save the spectrogram
        sg.Add(values);
        sg.SaveImage("kick.png", intensity: 5, dB: true);

        // create a Mel spectrogram too
        var mel = sg.GetBitmapMel(400, 100, dB: true);
        mel.Save("kick-mel.png");
    }

    static (double[] audio, int sampleRate) ReadWavMono(string filePath, double multiplier = 16_000)
    {
        using var afr = new NAudio.Wave.AudioFileReader(filePath);
        int sampleRate = afr.WaveFormat.SampleRate;
        int bytesPerSample = afr.WaveFormat.BitsPerSample / 8;
        int sampleCount = (int)(afr.Length / bytesPerSample);
        int channelCount = afr.WaveFormat.Channels;
        var audio = new List<double>(sampleCount);
        var buffer = new float[sampleRate * channelCount];
        int samplesRead = 0;
        while ((samplesRead = afr.Read(buffer, 0, buffer.Length)) > 0)
            audio.AddRange(buffer.Take(samplesRead).Select(x => x * multiplier));
        return (audio.ToArray(), sampleRate);
    }
}
```

![image](https://user-images.githubusercontent.com/4165489/139606011-58df0201-c1c8-4a0b-aff7-f01e3b4a18ea.png)

![image](https://user-images.githubusercontent.com/4165489/139606098-e44d23c1-663d-4c2e-9392-9a8f40e510ba.png)

You'll notice a couple things:
* The images do not look as good as the one produced by iZotope
* The mel-scaled image has black strips

I'll keep this brief but if you'd like me to discuss any of these topics in more detail, let me know. Here are my conclusions.

1. I can summarize this topic with "The Spectrogram package is designed to make spectrograms from large amounts of data." The task you described (analyzing extremely small amounts of data over extremely short periods of time) is outside the scope of what this package was designed for.

1. iZotope is doing a lot of "magic" in the frequency domain (vertical) and time domain (horizontal) to create their high quality image from extremely small amounts of input data. It's like non-linear anti-aliasing vertically, and carefully designed windowing and stepping horizontally. These functionalities are not built into this package, but if you wanted to you could implement it yourself. To do a deep dive into this, I recommend interacting with the [FftSharp](https://www.nuget.org/packages/FftSharp) package directly (not Spectrogram) to create FFTs using a highly customized FFT size and window. You can implement the non-linear Mel-scaling yourself.

1. This module's Mel scaling system requires the number of bins (rows of pixels on the output spectrogram) to be significantly fewer than the input data (original, non-scaled spectrogram). The intent of this package is to create ~500px high Mel spectrograms from ~5,000 px high linear scaled spectrograms. When this ratio isn't respected the Mel scale will appear with black bars where there is missing data. What I think iZotope is doing is filling these gaps in with data extrapolated from the adjacent bins. 

I know these explanations won't be particularly satisfying considering the type of images you're trying to achieve, but hopefully I was able to shed some light onto why the data is analyzed the way it is. If you want to achieve output similar to iZotope you probably can by writing some custom code interacting with the FFTs directly. Thanks for opening this issue! This topic (analyzing extremely small pieces of audio) isn't something I was really familiar with initially, and I'm happy we both got the opportunity to dive deeper into it.

Let me know if you have any more questions! Best of luck with your project 👍 🚀

**Comment by AlexandrSpirin** [comment]
Hi @swharden !
I went back to my project, studied the problem in more detail.
I use FFTSharp library for window selection, picked the one that looks better (Kaiser-Bessel). But I can not understand where and what exactly need to change the code to get extrapolated data from the neighboring cells to get a spectrogram without black bars.
From what I found in the free access - you can create "OverlapData" method to add data to fft list from neighboring array. But I can't do it correctly - as a result on spectrogram additional data is displayed at the top of spectrogram and it looks very strange.
I would be grateful for any instructions, and especially for code examples.

My current parameters for generating spectrogram: 
fftSize = 1024
stepSize = 4
sampleRate = 44100
melBinsCount = 256

I think if we can figure this problem out, it could be added as an additional option in your module

**Comment by swharden** [comment]
Hi @AlexandrSpirin,

Thanks for the follow-up!

> extrapolated data from the neighboring cells to get a spectrogram without black bars

Since I don't personally use Mel spectrograms, it's not very high priority for me to implement the interpolation functionality required to create the type of smooth non-linear spectrogram you're describing.

However, if you end up implementing this type of image interpolation yourself and finish creating a function that does it, I would be happy to review a pull request and merge your function into this package so others may use it as well!

Feel free to follow-up with additional comments here if you find additional information that would be useful to others interested in achieving a similar effect.

Thanks again for your comments, and good luck!
Scott
