### ISSUE TITLE
Using without a WAV file 

### ISSUE THREAD

**Issue by kkaiser41** [swharden/Spectrogram#40]
This is not really an issue but I didn't see another way to ask questions. Sorry if this is the wrong place.

Is there a way I could use this without pulling the data from a WAV file? Basically I have an array of doubles sampled at a specific rate that I would like to turn into a spectrogram. I want to see the frequency content over time or the frequency content against another signal other than time.

Thanks for any help you can offer.

**Comment by swharden** [comment]
> This is not really an issue but I didn't see another way to ask questions.

No worries, this works!

> Is there a way I could use this without pulling the data from a WAV file?

Check out the quickstart here:

https://github.com/swharden/Spectrogram#quickstart

Although this quickstart has a function that reads a WAV file, your `double[] audio` could be data from anything. It doesn't matter _where_ the data array comes from - this library (and FftSharp) works on `double[]` arrays 👍 

note: Depending on your goals FftSharp may be simpler if you don't need a 2D spectrogram https://github.com/swharden/FftSharp
