### ISSUE TITLE
Variable Height

### ISSUE THREAD

**Issue by rockandroll174** [swharden/Spectrogram#46]
Hello, I really like using your library, but there was a need to increase the height of the spectrogram picture, since I have to work at low purity (64 Hz)

**Comment by swharden** [comment]
Hi @rockandroll174, 

To increase the height (spectral resolution) of a spectrogram increase the `FftSize` defined when creating a `SpectrogramGenerator`. Increasing the FFT size will increase the spectral resolution, but represent more time in your signal. To counteract the time averaging effects you can decrease the `stepSize`.

Spectrograms are a balance of these things! In the end if it is still smaller than you desire you can get the Bitmap it produces and display it on a PictureBox stretched to any size. It will look blurry, but it will be larger!

Hope it helps
