### ISSUE TITLE
doubts about the code

### ISSUE THREAD

**Issue by adejonghm** [swharden/Spectrogram#5]
Do you have something like this developed in Python?
I want to do something like that, create the spectrogram for a .wav audio and play along with the plotted signal, but I'm using Python.

Thanks !!!

**Comment by swharden** [comment]
- https://github.com/swharden/Python-GUI-examples/tree/master/2016-07-37_qt_audio_monitor
- https://github.com/swharden/QRSS-VD
- https://www.youtube.com/watch?v=9Ti1pjuBic0
Hope that helps!
