### ISSUE TITLE
Support for .NET standard 2.0

### ISSUE THREAD

**Issue by ecsplendid** [swharden/Spectrogram#51]
Hello! Great library! 

I wondered if you considered supported a different image rendering approach rather than using the system.drawing stuff. It's not been possible to get your component working in Unity. I think the guy here was pointing out the same thing -- https://github.com/swharden/Spectrogram/pull/49

Cheers
Tim

**Comment by swharden** [comment]
Indeed! Using SkiaSharp (and not System.Drawing) is the primary change in ScottPlot 5 (currently in preview with limited features, but being actively developed)

http://scottplot.net/versions

**Comment by swharden** [comment]
Whoops, my bad! I didn't realize this is the Spectrogram library and not ScottPlot (another library I maintain) 😅 

I will leave this issue open an prioritize this! It definitely seems achievable.

Related:
* https://swharden.com/csdv/skiasharp/array-to-image/

**Comment by ecsplendid** [comment]
No prob! Thanks for coming back to me. I was able to use your underlying FftSharp library and render the spectrogram to a texture in real-time. Didn't look quite as nice as your one though, but got the job done ;)

**Comment by swharden** [comment]
Took a while to achieve this one, but I just pushed version 2.0.0-alpha (a preview version) to NuGet and it should work on any modern .NET platform
