### ISSUE TITLE
Render using SkiaSharp

### ISSUE THREAD

**Issue by swharden** [swharden/Spectrogram#52]
Now that System.Drawing.Common lost Linux support in .NET 7

Related: #49

**Comment by janjanusek** [comment]
I recommend using Sixlabors.Imagesharp images, very fast implementation, I implemented only grayscale spectrograms with that by extending ImageMaker class.

**Comment by vadd98** [comment]
Hi, sorry to bother. 
I'm using this really good library to generate spectrograms in my project on Linux but because of the System.Drawing.Common dependency I'm stuck on NET 6. Has there been any progress on the SkiaSharp rendering?

**Comment by janjanusek** [comment]
Don't do skiasharp man, I tried it's dead end. Do Sixlabors.Imagesharp it's working everywhere, very fast efficient, free AND as I wrote only need to create custom ImageMaker class which will be using this img lib, I didn't manage to update pixel array but only one by one pixel updating L8 bmp values but still lightning fast. I spent one whole day on skiasharp and didn't figure out so this was waay more easy to do.

**Comment by GeorgeS2019** [comment]
SkiaSharp allows this project to be used in Blazor
https://github.com/swharden/Spectrogram/pull/49

**Comment by vadd98** [comment]
Hi!
I created a pull request with a SkiaSharp implementation replacing the older System.Drawing.Common
https://github.com/swharden/Spectrogram/pull/61

**Comment by swharden** [comment]
publishing 2.0.0-alpha (a preview package) now, resolving this issue
